import type { AresV6Preset, AresV6PresetId } from './types';

// ═══════════════════════════════════════════════════════════════
// ARES ENGINE V6 — Preset Taxonomy
//
// These presets are the product language of the refoundation.
// They are intentionally more specific than the legacy 3-style model.
// ═══════════════════════════════════════════════════════════════

export const ARES_V6_PRESETS = [
  {
    id: 'STANDARD_PRO',
    publicName: 'Standard Pro',
    internalName: 'standard-pro-baseline',
    category: 'CORE',
    description: 'Configuración base segura para ranked: balance entre headshot, tracking y control de miras.',
    intendedFor: ['ranked general', 'primer resultado', 'usuarios nuevos', 'base para tuning'],
    sensitivityBias: { general: 0, redPoint: 0, scope2x: 0, scope4x: 0, sniperScope: 0, freeView: 0 },
    fireButtonBias: 0,
    gyroBias: 0,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD', 'TRAINING'],
    recommendedWeapons: ['AR_FAST', 'SMG', 'SHOTGUN'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'TODO_ROJO',
    publicName: 'Todo Rojo',
    internalName: 'red-dot-headshot-priority',
    category: 'HEADSHOT',
    description: 'Prioriza Punto Rojo y drag corto para subir la mira a cabeza sin volver incontrolables las miras largas.',
    intendedFor: ['headshot', 'drag', 'jugadores de corta distancia', 'M1887', 'Desert Eagle'],
    sensitivityBias: { general: 4, redPoint: 10, scope2x: 4, scope4x: -2, sniperScope: -6, freeView: 2 },
    fireButtonBias: 2,
    gyroBias: -2,
    recommendedModes: ['CLASH_SQUAD', 'TRAINING', 'CUSTOM_ROOM'],
    recommendedWeapons: ['SHOTGUN', 'PISTOL', 'SMG'],
    riskLevel: 'MEDIUM',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'X_METHOD',
    publicName: 'Modo Rojo X',
    internalName: 'x-method-dpi-drag',
    category: 'HEADSHOT',
    description: 'Preset inspirado en la intención de búsqueda Xenkzone: DPI por celular, arrastre a cabeza y valores agresivos pero explicados.',
    intendedFor: ['usuarios que buscan xenkzone', 'todo rojo', 'drag agresivo', 'LATAM'],
    sensitivityBias: { general: 6, redPoint: 12, scope2x: 5, scope4x: -3, sniperScope: -8, freeView: 5 },
    fireButtonBias: 3,
    gyroBias: -4,
    recommendedModes: ['CLASH_SQUAD', 'CUSTOM_ROOM', 'TRAINING'],
    recommendedWeapons: ['SHOTGUN', 'PISTOL', 'SMG'],
    riskLevel: 'ADVANCED',
    validationStatus: 'NEEDS_LAB_DATA',
  },
  {
    id: 'ONE_TAP',
    publicName: 'One Tap',
    internalName: 'one-tap-shotgun-pistol',
    category: 'WEAPON',
    description: 'Ajuste para M1887, M1014 y Desert Eagle: snap rápido, botón preciso y mira corta dominante.',
    intendedFor: ['M1887', 'M1014', 'Desert Eagle', 'clips', 'duelos cortos'],
    sensitivityBias: { general: 5, redPoint: 9, scope2x: 2, scope4x: -5, sniperScope: -10, freeView: 3 },
    fireButtonBias: -2,
    gyroBias: -4,
    recommendedModes: ['CLASH_SQUAD', 'LONE_WOLF', 'TRAINING'],
    recommendedWeapons: ['SHOTGUN', 'PISTOL'],
    riskLevel: 'ADVANCED',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'BRAZIL_RUSH',
    publicName: 'Brazil Rush',
    internalName: 'br-rush-cqb',
    category: 'HEADSHOT',
    description: 'Rush agresivo de corta distancia: General y Vista Libre más rápidos para entry fraggers.',
    intendedFor: ['rush', 'corta distancia', 'entry fragger', 'movimiento rápido'],
    sensitivityBias: { general: 8, redPoint: 8, scope2x: 2, scope4x: -4, sniperScope: -8, freeView: 10 },
    fireButtonBias: 4,
    gyroBias: -3,
    recommendedModes: ['CLASH_SQUAD', 'BATTLE_ROYALE', 'CUSTOM_ROOM'],
    recommendedWeapons: ['SMG', 'SHOTGUN', 'AR_FAST'],
    riskLevel: 'ADVANCED',
    validationStatus: 'NEEDS_LAB_DATA',
  },
  {
    id: 'CLASH_SQUAD',
    publicName: 'Clash Squad',
    internalName: 'cs-fast-rounds',
    category: 'MODE',
    description: 'Rondas cortas, compras rápidas, gloo wall y reacción inmediata. Reduce castigo en miras largas.',
    intendedFor: ['Clash Squad', 'rondas rápidas', 'gloo wall', 'duelos de corta-media'],
    sensitivityBias: { general: 5, redPoint: 6, scope2x: 1, scope4x: -4, sniperScope: -6, freeView: 5 },
    fireButtonBias: 2,
    gyroBias: -1,
    recommendedModes: ['CLASH_SQUAD'],
    recommendedWeapons: ['SHOTGUN', 'SMG', 'AR_FAST'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'BATTLE_ROYALE',
    publicName: 'Battle Royale',
    internalName: 'br-rotations-stability',
    category: 'MODE',
    description: 'Control estable para rotaciones, media distancia y late game. Menos extremo que Clash Squad.',
    intendedFor: ['Battle Royale', 'ranked BR', 'media distancia', 'rotaciones'],
    sensitivityBias: { general: 0, redPoint: 2, scope2x: 2, scope4x: 1, sniperScope: 0, freeView: 4 },
    fireButtonBias: 0,
    gyroBias: 0,
    recommendedModes: ['BATTLE_ROYALE'],
    recommendedWeapons: ['AR_FAST', 'AR_HEAVY', 'MARKSMAN', 'SNIPER'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'SNIPER_AWM',
    publicName: 'Sniper / AWM',
    internalName: 'awm-long-range-control',
    category: 'WEAPON',
    description: 'Reduce jitter y sobre-arrastre en 4x/AWM. Diseñado para quickscope controlado y largo alcance.',
    intendedFor: ['AWM', 'M24', 'M82B', 'long range', 'sniper mains'],
    sensitivityBias: { general: -8, redPoint: -4, scope2x: -3, scope4x: -8, sniperScope: -14, freeView: -2 },
    fireButtonBias: -4,
    gyroBias: 4,
    recommendedModes: ['BATTLE_ROYALE', 'CUSTOM_ROOM', 'TRAINING'],
    recommendedWeapons: ['SNIPER', 'MARKSMAN'],
    riskLevel: 'MEDIUM',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'LOW_END_STABLE',
    publicName: 'Low-End Stable',
    internalName: 'low-end-lag-control',
    category: 'DEVICE',
    description: 'Para celulares de 2–4GB RAM o 60Hz: compensa sensación pesada sin destruir control en 4x/AWM.',
    intendedFor: ['gama baja', '60Hz', '2GB RAM', '3GB RAM', '4GB RAM', 'lag'],
    sensitivityBias: { general: 6, redPoint: 5, scope2x: 0, scope4x: -6, sniperScope: -8, freeView: 2 },
    fireButtonBias: 4,
    gyroBias: -6,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD', 'TRAINING'],
    recommendedWeapons: ['SMG', 'SHOTGUN', 'AR_FAST'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'ANDROID_BUDGET',
    publicName: 'Android Budget',
    internalName: 'android-budget-touch-delay',
    category: 'DEVICE',
    description: 'Ajuste para Android económicos con input lag, panel LCD/IPS y FPS irregular.',
    intendedFor: ['Android gama baja', 'LCD', 'IPS', 'input lag', 'pantallas HD+'],
    sensitivityBias: { general: 5, redPoint: 5, scope2x: -1, scope4x: -6, sniperScope: -8, freeView: 2 },
    fireButtonBias: 5,
    gyroBias: -8,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD'],
    recommendedWeapons: ['SMG', 'SHOTGUN', 'AR_FAST'],
    riskLevel: 'SAFE',
    validationStatus: 'NEEDS_LAB_DATA',
  },
  {
    id: 'IPHONE_SMOOTH',
    publicName: 'iPhone Smooth',
    internalName: 'ios-high-ppi-control',
    category: 'DEVICE',
    description: 'Para iPhone con PPI alto y touch limpio: baja micro-jitter sin perder drag.',
    intendedFor: ['iPhone', 'iOS', 'PPI alto', 'OLED', 'touch estable'],
    sensitivityBias: { general: -4, redPoint: -2, scope2x: -2, scope4x: -4, sniperScope: -5, freeView: 0 },
    fireButtonBias: -2,
    gyroBias: 2,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD', 'TRAINING'],
    recommendedWeapons: ['AR_FAST', 'SHOTGUN', 'SNIPER'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'FOUR_FINGER_PRO',
    publicName: '4 Dedos Pro',
    internalName: 'four-finger-claw-pro',
    category: 'FINGERS',
    description: 'Garra competitiva: botón menor, más visibilidad y control simultáneo de mira, disparo y movimiento.',
    intendedFor: ['4 dedos', 'garra', 'competitivo', 'usuarios avanzados'],
    sensitivityBias: { general: -1, redPoint: 2, scope2x: 2, scope4x: 0, sniperScope: -2, freeView: 6 },
    fireButtonBias: -6,
    gyroBias: 2,
    recommendedModes: ['CLASH_SQUAD', 'BATTLE_ROYALE', 'TOURNAMENT'],
    recommendedWeapons: ['SHOTGUN', 'SMG', 'AR_FAST', 'SNIPER'],
    riskLevel: 'ADVANCED',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'THREE_FINGER_COMPETITIVE',
    publicName: '3 Dedos Competitivo',
    internalName: 'three-finger-standard',
    category: 'FINGERS',
    description: 'Punto medio ideal para subir de casual a competitivo sin rehacer todo el HUD.',
    intendedFor: ['3 dedos', 'transición desde 2 dedos', 'ranked', 'HUD competitivo'],
    sensitivityBias: { general: 0, redPoint: 2, scope2x: 1, scope4x: -1, sniperScope: -2, freeView: 2 },
    fireButtonBias: 0,
    gyroBias: 0,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD', 'TRAINING'],
    recommendedWeapons: ['SMG', 'AR_FAST', 'SHOTGUN'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'GYRO_LIGHT',
    publicName: 'Gyro Light',
    internalName: 'gyro-light-micro-corrections',
    category: 'GYRO',
    description: 'Giroscopio suave para micro-ajustes sin depender totalmente del sensor.',
    intendedFor: ['gyro principiante', 'micro ajuste', 'tracking', 'recoil leve'],
    sensitivityBias: { general: -2, redPoint: -1, scope2x: -2, scope4x: -3, sniperScope: -4, freeView: -2 },
    fireButtonBias: 0,
    gyroBias: 4,
    recommendedModes: ['BATTLE_ROYALE', 'CLASH_SQUAD', 'TRAINING'],
    recommendedWeapons: ['AR_FAST', 'AR_HEAVY', 'SMG'],
    riskLevel: 'SAFE',
    validationStatus: 'NEEDS_LAB_DATA',
  },
  {
    id: 'GYRO_PRO',
    publicName: 'Gyro Pro',
    internalName: 'gyro-pro-recoil-control',
    category: 'GYRO',
    description: 'Control avanzado de recoil con sensor: baja touch ligeramente y sube gyro para estabilidad.',
    intendedFor: ['gyro avanzado', 'recoil', '4 dedos', 'AR control'],
    sensitivityBias: { general: -5, redPoint: -3, scope2x: -4, scope4x: -6, sniperScope: -8, freeView: -4 },
    fireButtonBias: -2,
    gyroBias: 10,
    recommendedModes: ['BATTLE_ROYALE', 'TOURNAMENT', 'TRAINING'],
    recommendedWeapons: ['AR_HEAVY', 'MARKSMAN', 'SNIPER'],
    riskLevel: 'ADVANCED',
    validationStatus: 'NEEDS_LAB_DATA',
  },
  {
    id: 'SMG_TRACKING',
    publicName: 'SMG Tracking',
    internalName: 'smg-close-tracking',
    category: 'WEAPON',
    description: 'Para MP40/UMP: tracking fluido en corta-media, menos brusco que One Tap.',
    intendedFor: ['MP40', 'UMP', 'Thompson', 'tracking', 'close-mid range'],
    sensitivityBias: { general: 4, redPoint: 5, scope2x: 3, scope4x: -2, sniperScope: -6, freeView: 4 },
    fireButtonBias: 2,
    gyroBias: -1,
    recommendedModes: ['CLASH_SQUAD', 'BATTLE_ROYALE', 'TRAINING'],
    recommendedWeapons: ['SMG'],
    riskLevel: 'SAFE',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'SHOTGUN_DRAG',
    publicName: 'Shotgun Drag',
    internalName: 'shotgun-rotation-drag',
    category: 'WEAPON',
    description: 'Escopetas de un tiro: favorece J-drag/rotation drag y botón más cómodo para snap.',
    intendedFor: ['M1887', 'M1014', 'MAG-7', 'J-Drag', 'corta distancia'],
    sensitivityBias: { general: 6, redPoint: 8, scope2x: 1, scope4x: -5, sniperScope: -9, freeView: 4 },
    fireButtonBias: 4,
    gyroBias: -5,
    recommendedModes: ['CLASH_SQUAD', 'LONE_WOLF', 'TRAINING'],
    recommendedWeapons: ['SHOTGUN'],
    riskLevel: 'ADVANCED',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'AR_RECOIL_CONTROL',
    publicName: 'AR Recoil Control',
    internalName: 'ar-heavy-recoil-control',
    category: 'WEAPON',
    description: 'Rifles pesados y media distancia: reduce exceso en 4x y prioriza ráfagas controladas.',
    intendedFor: ['AK47', 'PARAFAL', 'Groza', '4x', 'recoil alto'],
    sensitivityBias: { general: -1, redPoint: 0, scope2x: -2, scope4x: -8, sniperScope: -6, freeView: 0 },
    fireButtonBias: -2,
    gyroBias: 3,
    recommendedModes: ['BATTLE_ROYALE', 'TOURNAMENT', 'TRAINING'],
    recommendedWeapons: ['AR_HEAVY', 'MARKSMAN'],
    riskLevel: 'MEDIUM',
    validationStatus: 'RESEARCH_BACKED',
  },
  {
    id: 'FREESTYLE_CLIPS',
    publicName: 'Freestyle Clips',
    internalName: 'freestyle-high-motion',
    category: 'HEADSHOT',
    description: 'Giros rápidos, free look alto y sensibilidad más viva para clips. No recomendado como primer preset ranked.',
    intendedFor: ['clips', 'freestyle', 'movimiento rápido', 'custom rooms'],
    sensitivityBias: { general: 10, redPoint: 8, scope2x: 2, scope4x: -4, sniperScope: -8, freeView: 14 },
    fireButtonBias: 2,
    gyroBias: -5,
    recommendedModes: ['CUSTOM_ROOM', 'TRAINING', 'LONE_WOLF'],
    recommendedWeapons: ['SHOTGUN', 'SMG', 'PISTOL'],
    riskLevel: 'ADVANCED',
    validationStatus: 'EXPERIMENTAL',
  },
  {
    id: 'CUSTOM_LAB',
    publicName: 'Custom Lab',
    internalName: 'custom-lab-expert-controls',
    category: 'LAB',
    description: 'Preset editable para usuarios avanzados. Todo cambio debe guardarse como versión y validarse con feedback.',
    intendedFor: ['usuarios premium', 'testing', 'A/B', 'laboratorio'],
    sensitivityBias: { general: 0, redPoint: 0, scope2x: 0, scope4x: 0, sniperScope: 0, freeView: 0 },
    fireButtonBias: 0,
    gyroBias: 0,
    recommendedModes: ['TRAINING', 'CUSTOM_ROOM'],
    recommendedWeapons: ['SHOTGUN', 'SMG', 'AR_FAST', 'AR_HEAVY', 'MARKSMAN', 'SNIPER', 'PISTOL'],
    riskLevel: 'ADVANCED',
    validationStatus: 'EXPERIMENTAL',
  },
] as const satisfies readonly AresV6Preset[];

export function getAresV6Preset(id: AresV6PresetId): AresV6Preset {
  const preset = ARES_V6_PRESETS.find((item) => item.id === id);
  if (!preset) {
    throw new Error(`ARES v6 preset not found: ${id}`);
  }
  return preset;
}

export function getAresV6PresetsByCategory(category: AresV6Preset['category']): AresV6Preset[] {
  return ARES_V6_PRESETS.filter((preset) => preset.category === category);
}
