// ═══════════════════════════════════════════════════════════════
// ARES-304 — Meta Analysis Configuration
// Datos del meta actual de Free Fire: armas, personajes, combos
// Editable desde admin API en /api/v1/admin/meta
// ═══════════════════════════════════════════════════════════════

export type WeaponTier = 'S' | 'A' | 'B' | 'C';
export type WeaponType = 'AR' | 'SMG' | 'SHOTGUN' | 'SNIPER' | 'PISTOL' | 'LMG' | 'MARKSMAN';

export interface WeaponMeta {
  name: string;
  type: WeaponType;
  tier: WeaponTier;
  damage: number;
  fireRate: number;
  range: number;
  accuracy: number;
  magazine: number;
  recoilControl: number;
  description: string;
  bestFor: string;
  combo: string;
}

export interface CharacterMeta {
  name: string;
  tier: WeaponTier;
  ability: string;
  abilityType: 'ACTIVE' | 'PASSIVE';
  description: string;
  bestCombo: string[];
}

export interface MetaSnapshot {
  version: string;
  lastUpdated: string;
  patchNotes: string;
  weapons: WeaponMeta[];
  characters: CharacterMeta[];
  topCombos: {
    name: string;
    description: string;
    weapons: string[];
    style: string;
  }[];
}

export const TIER_COLORS: Record<WeaponTier, { bg: string; text: string; border: string }> = {
  S: { bg: 'bg-red-500/20', text: 'text-red-400', border: 'border-red-500/30' },
  A: { bg: 'bg-orange-500/20', text: 'text-orange-400', border: 'border-orange-500/30' },
  B: { bg: 'bg-blue-500/20', text: 'text-blue-400', border: 'border-blue-500/30' },
  C: { bg: 'bg-slate-500/20', text: 'text-slate-400', border: 'border-slate-500/30' },
};

export const WEAPON_TYPE_LABELS: Record<WeaponType, string> = {
  AR: 'Rifle de Asalto',
  SMG: 'Subfusil',
  SHOTGUN: 'Escopeta',
  SNIPER: 'Francotirador',
  PISTOL: 'Pistola',
  LMG: 'Ametralladora',
  MARKSMAN: 'Tirador Designado',
};

export const CURRENT_META: MetaSnapshot = {
  version: 'OB51',
  lastUpdated: '2025-10-29',
  patchNotes: 'Buff a Parafal (+5% armor pen, +3% DMG), Thompson reworked con 2x scope, MAC10 upgrades mejorados, Winchester nueva marksman rifle, Nero nuevo personaje con Cryo Mind. Knockdown bleed-out reducido de 35s a 14s en rifles/snipers. Nuevo sistema de Loadouts.',
  weapons: [
    // ═══ TIER S — Meta-Defining ═══
    {
      name: 'M4A1',
      type: 'AR',
      tier: 'S',
      damage: 53,
      fireRate: 57,
      range: 79,
      accuracy: 55,
      magazine: 30,
      recoilControl: 85,
      description: 'El AR más consistente del juego. OB51 buffeó todos los niveles de upgrade: +5% DMG, +10% Accuracy. Bajo retroceso, buen daño, funciona a todas las distancias. La opción más segura para ranked.',
      bestFor: 'Todas las distancias',
      combo: 'M4A1 + MP40 o M4A1 + M1887',
    },
    {
      name: 'MP40',
      type: 'SMG',
      tier: 'S',
      damage: 48,
      fireRate: 83,
      range: 22,
      accuracy: 17,
      magazine: 20,
      recoilControl: 60,
      description: 'Rey absoluto del close range con la cadencia más alta del juego (830 RPM). OB50 añadió nuevos chips. Pierde 40% de daño pasados 10m pero dentro de ese rango no hay nada que lo supere.',
      bestFor: 'Combate cercano (<10m)',
      combo: 'MP40 + Woodpecker o MP40 + M4A1',
    },
    {
      name: 'AWM',
      type: 'SNIPER',
      tier: 'S',
      damage: 90,
      fireRate: 27,
      range: 91,
      accuracy: 90,
      magazine: 5,
      recoilControl: 20,
      description: 'One-shot headshot garantizado con cualquier casco incluyendo nivel 3. Viene con scope 8x preinstalado. Solo de airdrop. Define el control de sightlines en late-game.',
      bestFor: 'Larga distancia (100m+)',
      combo: 'AWM + Bizon o AWM + MP40',
    },
    {
      name: 'M1014',
      type: 'SHOTGUN',
      tier: 'S',
      damage: 94,
      fireRate: 39,
      range: 10,
      accuracy: 10,
      magazine: 6,
      recoilControl: 30,
      description: 'La mejor shotgun para squad wipes con 6 rondas en cargador. Devastadora en interiores y circles finales. Permite múltiples kills sin recargar.',
      bestFor: 'Interiores y rush',
      combo: 'M1014 + SCAR o M1014 + M4A1',
    },
    {
      name: 'MAC10',
      type: 'SMG',
      tier: 'S',
      damage: 25,
      fireRate: 75,
      range: 25,
      accuracy: 51,
      magazine: 42,
      recoilControl: 55,
      description: 'SMG de cargador largo (42 rondas). OB51 mejoró todos los upgrade paths: +5% DMG, +5% Precision, +5% Movement por nivel. Rompe armaduras y permite rush agresivo.',
      bestFor: 'Rush con armor breaking',
      combo: 'MAC10 + Woodpecker',
    },
    {
      name: 'Woodpecker',
      type: 'MARKSMAN',
      tier: 'S',
      damage: 85,
      fireRate: 38,
      range: 63,
      accuracy: 69,
      magazine: 12,
      recoilControl: 50,
      description: 'Mejor marksman rifle del juego. Penetración de armadura incorporada que ignora chalecos nivel 3. Precisión y daño excepcionales. Se combina perfectamente con MP40 para el meta de Gloo Wall.',
      bestFor: 'Media-larga distancia con armor pen',
      combo: 'Woodpecker + MP40',
    },
    // ═══ TIER A — Fuertes y confiables ═══
    {
      name: 'AK47',
      type: 'AR',
      tier: 'A',
      damage: 61,
      fireRate: 56,
      range: 72,
      accuracy: 41,
      magazine: 30,
      recoilControl: 55,
      description: 'Daño más alto por bala entre las AR comunes (560 RPM, 0.32s TTK). Retroceso vertical fuerte que requiere habilidad para controlar. Dominante en manos experimentadas.',
      bestFor: 'Media distancia (jugadores con control)',
      combo: 'AK47 + MP40',
    },
    {
      name: 'SCAR',
      type: 'AR',
      tier: 'A',
      damage: 53,
      fireRate: 61,
      range: 60,
      accuracy: 42,
      magazine: 30,
      recoilControl: 90,
      description: 'El AR definitivo para balanceado. Bajo retroceso, daño consistente a todas las distancias. 53 DMG con 61 RoF la hacen la opción más segura para ranked.',
      bestFor: 'Principiantes y ranked',
      combo: 'SCAR + M1014 o SCAR + M1887',
    },
    {
      name: 'MP5',
      type: 'SMG',
      tier: 'A',
      damage: 48,
      fireRate: 76,
      range: 41,
      accuracy: 54,
      magazine: 48,
      recoilControl: 65,
      description: 'TTK más bajo de toda la clase SMG (0.28s). Precisión alta y recarga rápida. OB51 añadió upgrade path. Mejor rango que MP40 pero menor cadencia.',
      bestFor: 'Corta-media distancia',
      combo: 'MP5 + AWM',
    },
    {
      name: 'UMP',
      type: 'SMG',
      tier: 'A',
      damage: 50,
      fireRate: 74,
      range: 37,
      accuracy: 43,
      magazine: 48,
      recoilControl: 70,
      description: 'SMG con penetración de armadura integrada. 50 DMG con 74 RoF es sólido. Cargador de 48 rondas para combates sostenidos. Excelente early-to-mid game.',
      bestFor: 'Corta-media con armor pen',
      combo: 'UMP + Sniper',
    },
    {
      name: 'M1887',
      type: 'SHOTGUN',
      tier: 'A',
      damage: 100,
      fireRate: 42,
      range: 21,
      accuracy: 10,
      magazine: 2,
      recoilControl: 20,
      description: 'Daño más alto por disparo del juego (100). Potencial de one-tap letal. Recarga rápida permite cadenas de eliminaciones. OB50 aplicó pequeño nerf de rango. Favorita de pushers agresivos.',
      bestFor: 'One-tap y rush agresivo',
      combo: 'M1887 + M4A1',
    },
    {
      name: 'Parafal',
      type: 'AR',
      tier: 'A',
      damage: 69,
      fireRate: 48,
      range: 58,
      accuracy: 40,
      magazine: 30,
      recoilControl: 50,
      description: 'Daño base más alto entre todas las AR (69). OB51 la buffeó fuerte: +5% Armor Pen, +3% DMG, +5% Accuracy. Cadencia lenta compensada por poder de frenado brutal. En ascenso en el meta competitivo.',
      bestFor: 'Media distancia (daño puro)',
      combo: 'Parafal + MP40 o Parafal + Winchester',
    },
    {
      name: 'M82B',
      type: 'SNIPER',
      tier: 'A',
      damage: 90,
      fireRate: 27,
      range: 85,
      accuracy: 90,
      magazine: 8,
      recoilControl: 15,
      description: 'Sniper con penetración de armadura y Gloo Walls. Cargador de 8 (el más grande entre snipers). OB50 nerfó penetración de Gloo Wall -15% pero sigue siendo muy fuerte.',
      bestFor: 'Anti-estructura y larga distancia',
      combo: 'M82B + MAC10',
    },
    {
      name: 'Desert Eagle',
      type: 'PISTOL',
      tier: 'A',
      damage: 90,
      fireRate: 33,
      range: 74,
      accuracy: 45,
      magazine: 7,
      recoilControl: 30,
      description: 'La pistola más poderosa del juego. 90 de daño con rango decente (74). Funciona como un sniper de bolsillo. Secundaria popular para loadouts de rush.',
      bestFor: 'Secundaria versátil',
      combo: 'Desert Eagle + cualquier primaria',
    },
    {
      name: 'XM8',
      type: 'AR',
      tier: 'A',
      damage: 57,
      fireRate: 60,
      range: 58,
      accuracy: 58,
      magazine: 25,
      recoilControl: 75,
      description: 'AR con scope 2x incorporado. Precisión más alta entre todas las AR (58). Retroceso extremadamente estable. Perfecta para especialistas de media distancia que prefieren consistencia.',
      bestFor: 'Media distancia (precisión)',
      combo: 'XM8 + M1014',
    },
    // ═══ TIER B — Situacionalmente fuertes ═══
    {
      name: 'FAMAS',
      type: 'AR',
      tier: 'B',
      damage: 54,
      fireRate: 72,
      range: 70,
      accuracy: 47,
      magazine: 30,
      recoilControl: 65,
      description: 'Ráfagas de 3 disparos. OB51 añadió upgrade path con +5% DMG por nivel. DPS teórico alto pero el patrón de ráfaga requiere ajuste. Buen rango (70).',
      bestFor: 'Media distancia (ráfagas)',
      combo: 'FAMAS + MP40',
    },
    {
      name: 'Groza',
      type: 'AR',
      tier: 'B',
      damage: 61,
      fireRate: 58,
      range: 77,
      accuracy: 52,
      magazine: 30,
      recoilControl: 60,
      description: 'Exclusiva de airdrop. Mismo daño que AK (61) con mejor rango (77) y precisión (52). 0.31s TTK. Monstruo en late-game pero difícil de obtener consistentemente.',
      bestFor: 'Late-game (airdrop only)',
      combo: 'Groza + Shotgun',
    },
    {
      name: 'P90',
      type: 'SMG',
      tier: 'B',
      damage: 49,
      fireRate: 76,
      range: 27,
      accuracy: 44,
      magazine: 50,
      recoilControl: 55,
      description: 'Cargador masivo de 50 rondas. Cadencia alta. Arma de supresión: spray-and-pray. Daño decente a media distancia a pesar de ser SMG.',
      bestFor: 'Supresión y spray',
      combo: 'P90 + AR',
    },
    {
      name: 'AN94',
      type: 'AR',
      tier: 'B',
      damage: 60,
      fireRate: 58,
      range: 55,
      accuracy: 48,
      magazine: 30,
      recoilControl: 60,
      description: 'OB50 buffeó +10% Accuracy. AR sólida con 60 DMG. Superada por AK y M4A1 en sus respectivos roles pero confiable como pickup temprano.',
      bestFor: 'Early-game pickup',
      combo: 'AN94 + SMG',
    },
    {
      name: 'Thompson',
      type: 'SMG',
      tier: 'B',
      damage: 50,
      fireRate: 77,
      range: 33,
      accuracy: 42,
      magazine: 42,
      recoilControl: 55,
      description: 'OB51 la buffeó enormemente: +3% DMG, +5% Armor Pen, +10% Range, +5% Accuracy, soporte para scope 2x. Subió de tier C a B sólido. Cargador de tambor de 42 rondas.',
      bestFor: 'Corta-media (post-buff)',
      combo: 'Thompson + Desert Eagle',
    },
    {
      name: 'Kar98k',
      type: 'SNIPER',
      tier: 'B',
      damage: 90,
      fireRate: 27,
      range: 84,
      accuracy: 90,
      magazine: 5,
      recoilControl: 25,
      description: 'Sniper bolt-action clásico. 90 DMG igual que AWM pero menos rango (84 vs 91). OB51 añadió upgrade path. One-shot headshot confiable.',
      bestFor: 'Sniper accesible (floor loot)',
      combo: 'Kar98k + MP5',
    },
    {
      name: 'SVD',
      type: 'MARKSMAN',
      tier: 'B',
      damage: 89,
      fireRate: 34,
      range: 80,
      accuracy: 51,
      magazine: 10,
      recoilControl: 35,
      description: 'Marksman rifle semi-auto. 89 DMG con 80 de rango. Disparo rápido de seguimiento comparado con snipers bolt. Solo airdrop. Gran velocidad de movimiento.',
      bestFor: 'Follow-up shots a distancia',
      combo: 'SVD + MAC10',
    },
    {
      name: 'M500',
      type: 'PISTOL',
      tier: 'B',
      damage: 45,
      fireRate: 44,
      range: 29,
      accuracy: 57,
      magazine: 12,
      recoilControl: 45,
      description: 'Pistola secundaria sólida. Mayor precisión que Desert Eagle pero menos daño. Buena opción de emergencia con cargador decente.',
      bestFor: 'Backup confiable',
      combo: 'M500 + cualquier primaria',
    },
    // ═══ TIER C — Nicho / Débiles ═══
    {
      name: 'M60',
      type: 'LMG',
      tier: 'C',
      damage: 56,
      fireRate: 55,
      range: 65,
      accuracy: 34,
      magazine: 60,
      recoilControl: 40,
      description: 'OB50 añadió slots de boca y culata. Denegación de área y fuego supresivo. Baja precisión y retroceso fuerte. Buena para destruir vehículos y Gloo Walls. Muy nicho.',
      bestFor: 'Supresión y anti-vehículo',
      combo: 'M60 + Shotgun (nicho)',
    },
    {
      name: 'Crossbow',
      type: 'SNIPER',
      tier: 'C',
      damage: 90,
      fireRate: 48,
      range: 36,
      accuracy: 41,
      magazine: 1,
      recoilControl: 10,
      description: 'Arma silenciosa. 90 de daño pero cargador de 1 ronda es devastador. Solo para emboscadas sigilosas. Extremadamente situacional.',
      bestFor: 'Emboscadas silenciosas',
      combo: 'No competitivo',
    },
    {
      name: 'CG15',
      type: 'SMG',
      tier: 'C',
      damage: 50,
      fireRate: 69,
      range: 71,
      accuracy: 60,
      magazine: 20,
      recoilControl: 50,
      description: 'Mecánica de carga para daño bonus con scope. Estilo de juego híbrido inusual. Buen rango para SMG (71) pero DPS efectivo lento. Inconsistente.',
      bestFor: 'Estilo híbrido (nicho)',
      combo: 'CG15 + Shotgun',
    },
    {
      name: 'VSS',
      type: 'SMG',
      tier: 'C',
      damage: 54,
      fireRate: 48,
      range: 82,
      accuracy: 73,
      magazine: 15,
      recoilControl: 60,
      description: 'Silenciada con scope integrado. OB50 buffeó cadencia. Alta precisión (73) y rango (82) para SMG. Daño y cargador limitan su efectividad real.',
      bestFor: 'Stealth y sigilo',
      combo: 'VSS + Shotgun',
    },
    {
      name: 'SPAS12',
      type: 'SHOTGUN',
      tier: 'C',
      damage: 97,
      fireRate: 42,
      range: 16,
      accuracy: 10,
      magazine: 5,
      recoilControl: 25,
      description: 'Inconsistente y poco confiable. 97 DMG en papel pero el spread la hace una apuesta. Superada por M1014 y M1887 en cada escenario posible.',
      bestFor: 'No recomendada',
      combo: 'Evitar — usar M1014 o M1887',
    },
  ],
  characters: [
    {
      name: 'Alok',
      tier: 'S',
      ability: 'Drop the Beat',
      abilityType: 'ACTIVE',
      description: 'Crea un aura de 5m que aumenta velocidad de movimiento 15% y cura 5 HP/s durante 10s. El personaje más versátil del juego para cualquier modo.',
      bestCombo: ['Jota', 'Hayato', 'Laura'],
    },
    {
      name: 'Nero',
      tier: 'S',
      ability: 'Cryo Mind',
      abilityType: 'ACTIVE',
      description: 'Lanza un dummy (150 HP, 12s) que vuela hasta 50m ignorando obstáculos. Rastrea al enemigo más cercano en 8m y explota creando una zona de sueño donde no se pueden colocar Gloo/Ice Walls y enemigos pierden 16 HP/s. CD: 45s.',
      bestCombo: ['Alok', 'Moco', 'Skyler'],
    },
    {
      name: 'Skyler',
      tier: 'S',
      ability: 'Riptide Rhythm',
      abilityType: 'ACTIVE',
      description: 'Libera una onda sónica que destruye hasta 5 Gloo Walls en 100m. Recupera HP al desplegar Gloo Walls propias. Clave en el meta actual de Gloo Wall rush.',
      bestCombo: ['Alok', 'Mr. Waggor', 'Jota'],
    },
    {
      name: 'Rin Yagami',
      tier: 'A',
      ability: 'Gale of Kunai',
      abilityType: 'PASSIVE',
      description: 'Genera un kunai cada 8s (max 3). Al impactar enemigo o Gloo Wall con arma, el kunai auto-persigue al objetivo causando hasta 12 de daño adicional. OB51 buffeó velocidad y daño.',
      bestCombo: ['Alok', 'Laura', 'Hayato'],
    },
    {
      name: 'Laura',
      tier: 'A',
      ability: 'Sharp Shooter',
      abilityType: 'PASSIVE',
      description: 'Aumenta precisión 60% mientras usa scope (buffeada de 50% en OB50). Esencial para builds de sniper y marksman.',
      bestCombo: ['Moco', 'Rafael', 'Shirou'],
    },
    {
      name: 'Jota',
      tier: 'A',
      ability: 'Sustained Raids',
      abilityType: 'PASSIVE',
      description: 'Recupera HP al eliminar enemigos con SMG o Shotgun. Sinergia perfecta con el meta de rush agresivo MP40/M1014.',
      bestCombo: ['Alok', 'Hayato', 'Kelly'],
    },
    {
      name: 'Chrono',
      tier: 'A',
      ability: 'Time Turner',
      abilityType: 'ACTIVE',
      description: 'Crea un escudo temporal que bloquea daño frontal. Permite disparar a través del escudo. Ideal para combates 1v1 y pushes agresivos.',
      bestCombo: ['Alok', 'Shirou', 'Moco'],
    },
    {
      name: 'Hayato',
      tier: 'A',
      ability: 'Bushido',
      abilityType: 'PASSIVE',
      description: 'Aumenta daño de penetración de armadura proporcionalmente al HP perdido. Máximo efecto con HP bajo — high risk, high reward.',
      bestCombo: ['Alok', 'Jota', 'Kelly'],
    },
    {
      name: 'Moco',
      tier: 'A',
      ability: "Hacker's Eye",
      abilityType: 'PASSIVE',
      description: 'Marca a enemigos impactados durante 5s para todo el equipo. Intel invaluable en squad ranked. Permite coordinar ataques.',
      bestCombo: ['Laura', 'Shirou', 'Alok'],
    },
    {
      name: 'Wukong',
      tier: 'B',
      ability: 'Camouflage',
      abilityType: 'ACTIVE',
      description: 'Se transforma en arbusto para camuflarse. Útil para emboscadas y flanqueos. Menos relevante en el meta actual de rush agresivo.',
      bestCombo: ['Alok', 'Kelly', 'Hayato'],
    },
    {
      name: 'Shirou',
      tier: 'B',
      ability: 'Damage Delivered',
      abilityType: 'PASSIVE',
      description: 'Marca a enemigos que te disparan dentro de 80m. Primer disparo tiene penetración de armadura extra. Contramedida defensiva.',
      bestCombo: ['Chrono', 'Moco', 'Alok'],
    },
    {
      name: 'Kelly',
      tier: 'B',
      ability: 'Dash',
      abilityType: 'PASSIVE',
      description: 'Aumenta velocidad de sprint 6%. Awakened Kelly añade daño extra al primer disparo después de correr. Complemento para rush.',
      bestCombo: ['Alok', 'Hayato', 'Jota'],
    },
  ],
  topCombos: [
    {
      name: 'Gloo Wall Rush (Meta Dominante)',
      description: 'Spam Gloo Walls para cobertura, rush con SMG cercano, Woodpecker a distancia. El estilo más usado en competitivo.',
      weapons: ['MP40', 'Woodpecker'],
      style: 'aggressive',
    },
    {
      name: 'Balanceado Competitivo',
      description: 'El combo más confiable para ranked. SCAR spray a media distancia, M1014 para cerrar kills en interiores.',
      weapons: ['SCAR', 'M1014'],
      style: 'balanced',
    },
    {
      name: 'Sniper Control',
      description: 'AWM para one-tap headshots a distancia, Bizon para defensa cercana. Domina sightlines en late-game.',
      weapons: ['AWM', 'MP5'],
      style: 'sniper',
    },
    {
      name: 'Armor Breaker',
      description: 'Ambas armas penetran armadura, TTK rapidísimo. Perfecto contra enemigos con chaleco nivel 3.',
      weapons: ['MAC10', 'Woodpecker'],
      style: 'aggressive',
    },
    {
      name: 'Winchester Burst (Nuevo OB51)',
      description: 'Winchester para ráfagas a media distancia, Parafal buffeada como backup de daño puro. Estilo emergente post-OB51.',
      weapons: ['Winchester', 'Parafal'],
      style: 'balanced',
    },
    {
      name: 'Versatile Classic',
      description: 'M4A1 estable para todo rango + M1887 one-tap en close. Equilibrio perfecto entre seguridad y agresividad.',
      weapons: ['M4A1', 'M1887'],
      style: 'balanced',
    },
  ],
};
